// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Ejercicio4Modulo2.Domain.Entity;

namespace Ejercicio4Modulo2.Repository
{
    public partial class Ejercicio4Modulo2Context : DbContext
    {
        public Ejercicio4Modulo2Context()
        {
        }

        public Ejercicio4Modulo2Context(DbContextOptions<Ejercicio4Modulo2Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Parametrium> Parametria { get; set; }
        public virtual DbSet<Rechazo> Rechazos { get; set; }
        public virtual DbSet<VentasMensuale> VentasMensuales { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Parametrium>(entity =>
            {
                entity.ToTable("parametria");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Key)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("key");

                entity.Property(e => e.Value)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("value");
            });

            modelBuilder.Entity<Rechazo>(entity =>
            {
                entity.ToTable("rechazos");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Error)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("error");

                entity.Property(e => e.RegistroOriginal)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("registro_original");
            });

            modelBuilder.Entity<VentasMensuale>(entity =>
            {
                entity.ToTable("ventas_mensuales");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CodVendedor)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("cod_vendedor");

                entity.Property(e => e.Fecha)
                    .HasColumnType("datetime")
                    .HasColumnName("fecha");

                entity.Property(e => e.Venta)
                    .HasColumnType("numeric(11, 2)")
                    .HasColumnName("venta");

                entity.Property(e => e.VentaEmpresaGrande).HasColumnName("venta_empresa_grande");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}