// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ejercicio4Modulo2.Domain.Entity
{
    public partial class Parametrium
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    }
}