// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ejercicio4Modulo2.Domain.Entity
{
    public partial class VentasMensuale
    {
        public int Id { get; set; }
        public DateTime Fecha { get; set; }
        public string CodVendedor { get; set; }
        public decimal Venta { get; set; }
        public bool VentaEmpresaGrande { get; set; }
    }
}